# Generated by Django 6.0.1 on 2026-01-10 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_customuser_birthday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='complete_name',
            new_name='full_name',
        ),
    ]
