# Generated by Django 6.0.1 on 2026-01-13 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_customuser_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='picture',
            field=models.CharField(blank=True, null=True),
        ),
    ]
