# Generated by Django 5.1.6 on 2026-03-05 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_add_seller_stripe_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_seller',
        ),
    ]
