# Generated by Django 5.1.6 on 2026-03-14 19:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_created_ws', models.BooleanField(default=True)),
                ('order_created_email', models.BooleanField(default=True)),
                ('order_status_changed_ws', models.BooleanField(default=True)),
                ('order_status_changed_email', models.BooleanField(default=True)),
                ('payment_confirmed_ws', models.BooleanField(default=True)),
                ('payment_confirmed_email', models.BooleanField(default=True)),
                ('payment_failed_ws', models.BooleanField(default=True)),
                ('payment_failed_email', models.BooleanField(default=True)),
                ('dispute_opened_ws', models.BooleanField(default=True)),
                ('dispute_opened_email', models.BooleanField(default=True)),
                ('shipment_created_ws', models.BooleanField(default=True)),
                ('shipment_created_email', models.BooleanField(default=True)),
                ('shipment_status_updated_ws', models.BooleanField(default=True)),
                ('shipment_status_updated_email', models.BooleanField(default=False)),
                ('delivery_scheduled_ws', models.BooleanField(default=True)),
                ('delivery_scheduled_email', models.BooleanField(default=True)),
                ('delivery_confirmed_ws', models.BooleanField(default=True)),
                ('delivery_confirmed_email', models.BooleanField(default=True)),
                ('new_message_ws', models.BooleanField(default=True)),
                ('new_message_email', models.BooleanField(default=False)),
                ('seller_verified_ws', models.BooleanField(default=True)),
                ('seller_verified_email', models.BooleanField(default=True)),
                ('listing_blocked_ws', models.BooleanField(default=True)),
                ('listing_blocked_email', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preferência de Notificação',
                'verbose_name_plural': 'Preferências de Notificação',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('order_created', 'Pedido Criado'), ('order_status_changed', 'Status do Pedido Alterado'), ('payment_confirmed', 'Pagamento Confirmado'), ('payment_failed', 'Falha no Pagamento'), ('dispute_opened', 'Disputa Aberta'), ('shipment_created', 'Envio Criado'), ('shipment_status_updated', 'Status do Envio Atualizado'), ('delivery_scheduled', 'Entrega Agendada'), ('delivery_confirmed', 'Entrega Confirmada'), ('new_message', 'Nova Mensagem'), ('seller_verified', 'Vendedor Verificado'), ('listing_blocked', 'Anúncio Bloqueado')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('idempotency_key', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', '-created_at'], name='notificatio_recipie_684eac_idx')],
            },
        ),
    ]
