# Generated by Django 5.1.6 on 2026-03-14 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='listing_created_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='listing_created_ws',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('order_created', 'Pedido Criado'), ('order_status_changed', 'Status do Pedido Alterado'), ('payment_confirmed', 'Pagamento Confirmado'), ('payment_failed', 'Falha no Pagamento'), ('dispute_opened', 'Disputa Aberta'), ('shipment_created', 'Envio Criado'), ('shipment_status_updated', 'Status do Envio Atualizado'), ('delivery_scheduled', 'Entrega Agendada'), ('delivery_confirmed', 'Entrega Confirmada'), ('new_message', 'Nova Mensagem'), ('seller_verified', 'Vendedor Verificado'), ('listing_blocked', 'Anúncio Bloqueado'), ('listing_created', 'Anúncio Publicado')], max_length=50),
        ),
    ]
