# Generated by Django 6.0.1 on 2026-02-07 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_payment_method_order_shipping_services_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Aguardando Pagamento'), ('paid', 'Pagamento Confirmado'), ('processing', 'Em Processamento'), ('shipped', 'Enviado'), ('delivered', 'Entregue'), ('cancelled', 'Cancelado'), ('failed', 'Falha no Pagamento'), ('refunded', 'Reembolsado')], default='pending_payment', max_length=20),
        ),
    ]
