# Generated by Django 5.1.6 on 2026-02-15 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_update_order_status_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Aguardando Pagamento'), ('paid', 'Pagamento Confirmado'), ('processing', 'Aguardando Envio'), ('shipped', 'Enviado'), ('delivered', 'Entregue'), ('cancelled', 'Cancelado'), ('failed', 'Falha no Pagamento'), ('refunded', 'Reembolsado')], default='pending_payment', max_length=20),
        ),
    ]
