# Generated by Django 6.0.1 on 2026-01-16 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='marketplacelisting',
            name='sold_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
