# Generated by Django 6.0.1 on 2026-01-17 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_code_alter_marketplacelisting_sold_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketplacelistingimages',
            name='image',
        ),
        migrations.AddField(
            model_name='marketplacelistingimages',
            name='image_url',
            field=models.URLField(default='test', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marketplacelistingimages',
            name='object_name',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
    ]
