# Generated by Django 5.1.6 on 2026-02-14 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_marketplacelistingimages_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplacelisting',
            name='title',
            field=models.CharField(default='', help_text='Título do anúncio', max_length=150),
        ),
        migrations.AlterField(
            model_name='marketplacelisting',
            name='description',
            field=models.TextField(max_length=255),
        ),
    ]
