# Generated by Django 5.1.6 on 2026-02-14 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_marketplacelisting_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplacelisting',
            name='title',
            field=models.CharField(help_text='Título do anúncio', max_length=150),
        ),
    ]
