# Generated by Django 5.1.6 on 2026-02-14 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0005_add_completion_confirmation_fields'),
        ('products', '0005_alter_marketplacelisting_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplacelisting',
            name='shipping_address',
            field=models.ForeignKey(blank=True, help_text='Endereço de envio do anúncio', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='logistics.address'),
        ),
    ]
