# Generated by Django 5.1.6 on 2026-02-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_marketplacelisting_shipping_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
