# Generated by Django 5.1.6 on 2026-02-22 17:02

import django.db.models.deletion
from django.db import migrations, models


def migrate_listing_dimensions_to_packages(apps, schema_editor):
    """
    Para cada MarketplaceListing que possui dimensões preenchidas nos campos
    legados (weight_kg, height_cm, width_cm, length_cm), cria um ListingPackage
    correspondente com esses valores.

    Esta migração de dados é necessária para manter a compatibilidade retroativa
    ao introduzir suporte a múltiplos pacotes por anúncio.
    """
    MarketplaceListing = apps.get_model('products', 'MarketplaceListing')
    ListingPackage = apps.get_model('products', 'ListingPackage')

    packages_to_create = []
    for listing in MarketplaceListing.objects.filter(
        weight_kg__isnull=False,
        height_cm__isnull=False,
        width_cm__isnull=False,
        length_cm__isnull=False,
    ):
        packages_to_create.append(
            ListingPackage(
                listing=listing,
                weight_kg=listing.weight_kg,
                height_cm=listing.height_cm,
                width_cm=listing.width_cm,
                length_cm=listing.length_cm,
                description='Pacote principal (migrado automaticamente)',
            )
        )

    if packages_to_create:
        ListingPackage.objects.bulk_create(packages_to_create)


def reverse_migrate_listing_dimensions(apps, schema_editor):
    """
    Reverso: restaura as dimensões dos campos legados a partir dos pacotes
    criados pela migração direta, e depois remove esses pacotes.

    Apenas restaura listings que ainda não têm dimensões preenchidas
    (para não sobrescrever dados editados manualmente).
    """
    MarketplaceListing = apps.get_model('products', 'MarketplaceListing')
    ListingPackage = apps.get_model('products', 'ListingPackage')

    for pkg in ListingPackage.objects.filter(
        description='Pacote principal (migrado automaticamente)'
    ):
        listing = pkg.listing
        if not listing.weight_kg:
            listing.weight_kg = pkg.weight_kg
            listing.height_cm = pkg.height_cm
            listing.width_cm = pkg.width_cm
            listing.length_cm = pkg.length_cm
            listing.save(update_fields=['weight_kg', 'height_cm', 'width_cm', 'length_cm'])
        pkg.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_increase_product_slug_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplacelisting',
            name='height_cm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Altura em cm (legado — use packages)', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='marketplacelisting',
            name='length_cm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Comprimento em cm (legado — use packages)', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='marketplacelisting',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Peso em kg (legado — use packages)', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='marketplacelisting',
            name='width_cm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Largura em cm (legado — use packages)', max_digits=6, null=True),
        ),
        migrations.CreateModel(
            name='ListingPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_kg', models.DecimalField(decimal_places=2, help_text='Peso do pacote em kg', max_digits=6)),
                ('height_cm', models.DecimalField(decimal_places=2, help_text='Altura do pacote em cm', max_digits=6)),
                ('width_cm', models.DecimalField(decimal_places=2, help_text='Largura do pacote em cm', max_digits=6)),
                ('length_cm', models.DecimalField(decimal_places=2, help_text='Comprimento do pacote em cm', max_digits=6)),
                ('description', models.CharField(blank=True, help_text="Descrição opcional do pacote (ex: 'Caixa grande')", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='products.marketplacelisting')),
            ],
            options={
                'verbose_name': 'Pacote do Anúncio',
                'verbose_name_plural': 'Pacotes do Anúncio',
                'ordering': ['id'],
            },
        ),
        migrations.RunPython(
            migrate_listing_dimensions_to_packages,
            reverse_code=reverse_migrate_listing_dimensions,
        ),
    ]
