# Generated by Django 5.1.6 on 2026-02-28 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_add_listing_packages'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplacelisting',
            name='shipping_method',
            field=models.CharField(choices=[('in_person', 'Somente Entrega Presencial'), ('melhor_envio', 'Somente Melhor Envio'), ('both', 'Ambos (Presencial e Melhor Envio)')], default='both', help_text="Método de envio aceito pelo vendedor para este anúncio. 'in_person' = somente entrega presencial; 'melhor_envio' = somente via transportadora; 'both' = ambos os métodos são aceitos.", max_length=20),
        ),
    ]
