# Generated by Django 5.1.6 on 2026-03-17 00:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
        ('orders', '0004_update_processing_label'),
        ('products', '0010_add_shipping_method_to_marketplace_listing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(condition=models.Q(('conversation_type', 'buyer_seller'), ('status', 'active')), fields=('conversation_type', 'listing'), name='unique_active_buyer_seller_per_listing'),
        ),
    ]
