# Generated by Django 5.1.6 on 2026-03-04 23:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='platform_fee_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='transfer_group',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_dispute_id', models.CharField(max_length=255, unique=True)),
                ('stripe_charge_id', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='BRL', max_length=3)),
                ('reason', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('reversal_attempted', models.BooleanField(default=False)),
                ('reversal_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stripe_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disputes', to='payments.payment')),
            ],
            options={
                'verbose_name': 'Disputa',
                'verbose_name_plural': 'Disputas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('platform_fee_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stripe_transfer_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('transfer_status', models.CharField(choices=[('pending', 'Pendente'), ('dispatched', 'Despachado'), ('failed', 'Falhou')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='splits', to='payments.payment')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_splits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Split de Pagamento',
                'verbose_name_plural': 'Splits de Pagamento',
                'ordering': ['-created_at'],
                'unique_together': {('payment', 'seller')},
            },
        ),
    ]
