# Generated by Django 5.1.6 on 2026-03-05 17:12

import authentication.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_remove_is_seller'),
        ('payments', '0002_add_payment_split_dispute_transfer_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerConnectedAccountProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Conta Conectada Stripe',
                'verbose_name_plural': 'Contas Conectadas Stripe',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('authentication.customuser',),
            managers=[
                ('objects', authentication.models.CustomUserManager()),
            ],
        ),
    ]
