# Generated by Django 5.1.6 on 2026-03-15 16:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_update_processing_label'),
        ('payments', '0004_paymentsplit_product_shipping_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('requested', 'Solicitado'), ('seller_reviewing', 'Em Análise pelo Vendedor'), ('auto_approved', 'Aprovado Automaticamente'), ('approved', 'Aprovado pelo Vendedor'), ('rejected', 'Rejeitado pelo Vendedor'), ('escalated', 'Escalado para Plataforma'), ('platform_approved', 'Aprovado pela Plataforma'), ('platform_rejected', 'Rejeitado pela Plataforma'), ('stripe_refund_pending', 'Reembolso Stripe Pendente'), ('refunded', 'Reembolsado'), ('withdrawn', 'Retirado pelo Comprador'), ('closed', 'Encerrado')], default='requested', max_length=30)),
                ('refund_type', models.CharField(choices=[('remorse', 'Arrependimento'), ('defective', 'Produto com Defeito / Diferente'), ('not_received', 'Produto Não Recebido'), ('duplicate_charge', 'Cobrança Duplicada'), ('platform_decision', 'Decisão da Plataforma')], max_length=30)),
                ('amount_requested', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_approved', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('reason_buyer', models.TextField()),
                ('reason_seller', models.TextField(blank=True)),
                ('reason_platform', models.TextField(blank=True)),
                ('evidence_urls', models.JSONField(default=list)),
                ('seller_evidence_urls', models.JSONField(default=list)),
                ('seller_deadline', models.DateTimeField(blank=True, null=True)),
                ('escalation_deadline', models.DateTimeField(blank=True, null=True)),
                ('stripe_refund_id', models.CharField(blank=True, max_length=100)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_requests_decided', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refund_requests', to='orders.order')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refund_requests', to='payments.payment')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refund_requests_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitação de Reembolso',
                'verbose_name_plural': 'Solicitações de Reembolso',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RefundRequestHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=30)),
                ('to_status', models.CharField(max_length=30)),
                ('actor_type', models.CharField(choices=[('buyer', 'Comprador'), ('seller', 'Vendedor'), ('system', 'Sistema'), ('platform', 'Plataforma')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('refund_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='payments.refundrequest')),
            ],
            options={
                'verbose_name': 'Histórico de Solicitação de Reembolso',
                'verbose_name_plural': 'Históricos de Solicitações de Reembolso',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='refundrequest',
            index=models.Index(fields=['status', 'seller_deadline'], name='payments_re_status_d6b011_idx'),
        ),
        migrations.AddIndex(
            model_name='refundrequest',
            index=models.Index(fields=['status', 'escalation_deadline'], name='payments_re_status_83c672_idx'),
        ),
        migrations.AddIndex(
            model_name='refundrequest',
            index=models.Index(fields=['payment', 'status'], name='payments_re_payment_58c7e0_idx'),
        ),
    ]
