# Generated by Django 5.1.6 on 2026-03-19 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_add_seller_to_order'),
        ('payments', '0005_add_refund_request_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_for', models.DateTimeField(help_text='Data/hora a partir da qual o repasse pode ser executado (delivered_at + PAYOUT_DAYS)')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('dispatched', 'Despachado'), ('failed', 'Falhou')], db_index=True, default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_transfer', to='orders.order')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_transfers', to='payments.payment')),
            ],
            options={
                'verbose_name': 'Repasse Agendado',
                'verbose_name_plural': 'Repasses Agendados',
                'ordering': ['scheduled_for'],
                'indexes': [models.Index(fields=['status', 'scheduled_for'], name='payments_sc_status_a891b1_idx')],
            },
        ),
    ]
