# Generated by Django 6.0.1 on 2026-01-29 23:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('home', 'Residencial'), ('work', 'Comercial'), ('shipping', 'Envio (Vendedor)'), ('other', 'Outro')], default='home', max_length=20)),
                ('nickname', models.CharField(blank=True, max_length=50)),
                ('is_shipping_address', models.BooleanField(default=False)),
                ('recipient_name', models.CharField(max_length=200)),
                ('recipient_phone', models.CharField(max_length=20)),
                ('zipcode', models.CharField(max_length=9)),
                ('street', models.CharField(max_length=200)),
                ('number', models.CharField(max_length=20)),
                ('complement', models.CharField(blank=True, max_length=100)),
                ('neighborhood', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('country', models.CharField(default='BR', max_length=2)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('melhorenvio_order_id', models.CharField(max_length=255, unique=True)),
                ('melhorenvio_tracking_code', models.CharField(blank=True, max_length=255)),
                ('carrier_name', models.CharField(max_length=100)),
                ('carrier_service', models.CharField(max_length=100)),
                ('shipping_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('insurance_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('posted', 'Postado'), ('in_transit', 'Em Trânsito'), ('out_for_delivery', 'Saiu para Entrega'), ('delivered', 'Entregue'), ('cancelled', 'Cancelado'), ('returned', 'Devolvido')], default='pending', max_length=20)),
                ('tracking_url', models.URLField(blank=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('height', models.DecimalField(decimal_places=2, max_digits=6)),
                ('width', models.DecimalField(decimal_places=2, max_digits=6)),
                ('length', models.DecimalField(decimal_places=2, max_digits=6)),
                ('origin_address', models.JSONField()),
                ('destination_address', models.JSONField()),
                ('label_url', models.URLField(blank=True)),
                ('label_generated_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_delivery_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='orders.order')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Envio',
                'verbose_name_plural': 'Envios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('location', models.CharField(blank=True, max_length=255)),
                ('occurred_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_history', to='logistics.shipment')),
            ],
            options={
                'verbose_name': 'Rastreamento',
                'verbose_name_plural': 'Rastreamentos',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='ShippingQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_zipcode', models.CharField(max_length=9)),
                ('origin_address', models.JSONField()),
                ('destination_zipcode', models.CharField(max_length=9)),
                ('destination_address', models.JSONField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('height', models.DecimalField(decimal_places=2, max_digits=6)),
                ('width', models.DecimalField(decimal_places=2, max_digits=6)),
                ('length', models.DecimalField(decimal_places=2, max_digits=6)),
                ('declared_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quotes_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_quotes_as_seller', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_quotes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cotação de Frete',
                'verbose_name_plural': 'Cotações de Frete',
                'ordering': ['-created_at'],
            },
        ),
    ]
