# Generated by Django 6.0.1 on 2026-02-07 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
        ('orders', '0003_update_order_status_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InPersonDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_status', models.CharField(choices=[('pending_schedule', 'Aguardando Agendamento'), ('scheduled', 'Agendado'), ('confirmed', 'Confirmado por Ambas as Partes'), ('in_progress', 'Em Andamento'), ('completed', 'Concluído'), ('cancelled', 'Cancelado'), ('no_show', 'Não Compareceu')], default='pending_schedule', max_length=20)),
                ('meeting_location_name', models.CharField(help_text='Nome do local (ex: Shopping X, Estação Y)', max_length=200)),
                ('meeting_address', models.JSONField(help_text='Endereço completo do local de encontro')),
                ('meeting_notes', models.TextField(blank=True, help_text='Observações sobre o local (ex: próximo à entrada principal)')),
                ('scheduled_date', models.DateField(blank=True, help_text='Data agendada para o encontro', null=True)),
                ('scheduled_time', models.TimeField(blank=True, help_text='Horário agendado para o encontro', null=True)),
                ('seller_contact_phone', models.CharField(help_text='Telefone do vendedor para contato', max_length=20)),
                ('buyer_contact_phone', models.CharField(help_text='Telefone do comprador para contato', max_length=20)),
                ('seller_confirmed', models.BooleanField(default=False)),
                ('buyer_confirmed', models.BooleanField(default=False)),
                ('seller_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('buyer_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('completion_notes', models.TextField(blank=True, help_text='Observações sobre a conclusão da entrega')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='in_person_deliveries_as_buyer', to=settings.AUTH_USER_MODEL)),
                ('completed_by', models.ForeignKey(blank=True, help_text='Quem confirmou a conclusão da entrega', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_deliveries', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='in_person_deliveries_as_seller', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entrega Presencial',
                'verbose_name_plural': 'Entregas Presenciais',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_method', models.CharField(choices=[('shipping', 'Envio via Transportadora'), ('in_person', 'Retirada Presencial')], default='shipping', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('confirmed', 'Confirmado'), ('ready', 'Pronto para Retirada/Envio'), ('in_transit', 'Em Trânsito'), ('delivered', 'Entregue/Retirado'), ('cancelled', 'Cancelado'), ('failed', 'Falhou')], default='pending', max_length=20)),
                ('delivery_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('in_person_delivery', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_delivery', to='logistics.inpersondelivery')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='orders.order')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_deliveries', to=settings.AUTH_USER_MODEL)),
                ('shipment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_delivery', to='logistics.shipment')),
            ],
            options={
                'verbose_name': 'Entrega do Pedido',
                'verbose_name_plural': 'Entregas do Pedido',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order_delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='logistics.orderdelivery')),
            ],
            options={
                'verbose_name': 'Log de Status de Entrega',
                'verbose_name_plural': 'Logs de Status de Entrega',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='inpersondelivery',
            index=models.Index(fields=['seller', 'buyer'], name='logistics_i_seller__9615bb_idx'),
        ),
        migrations.AddIndex(
            model_name='inpersondelivery',
            index=models.Index(fields=['meeting_status'], name='logistics_i_meeting_006ce9_idx'),
        ),
        migrations.AddIndex(
            model_name='inpersondelivery',
            index=models.Index(fields=['scheduled_date', 'scheduled_time'], name='logistics_i_schedul_d614bc_idx'),
        ),
        migrations.AddIndex(
            model_name='orderdelivery',
            index=models.Index(fields=['order', 'seller'], name='logistics_o_order_i_f4a027_idx'),
        ),
        migrations.AddIndex(
            model_name='orderdelivery',
            index=models.Index(fields=['delivery_method', 'status'], name='logistics_o_deliver_daefb9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='orderdelivery',
            unique_together={('order', 'seller')},
        ),
    ]
