# Generated by Django 5.1.6 on 2026-02-12 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_inpersondelivery_orderdelivery_deliverystatuslog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarrierRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier_name', models.CharField(help_text='Nome da transportadora como retornado pelo Melhor Envio (ex: Correios, Jadlog)', max_length=100)),
                ('modality', models.CharField(help_text='Nome da modalidade/serviço (ex: SEDEX/PAC, Mini Envios, Jadlog Pegaki)', max_length=200)),
                ('min_height', models.DecimalField(blank=True, decimal_places=2, help_text='Altura mínima em cm', max_digits=6, null=True)),
                ('min_width', models.DecimalField(blank=True, decimal_places=2, help_text='Largura mínima em cm', max_digits=6, null=True)),
                ('min_length', models.DecimalField(blank=True, decimal_places=2, help_text='Comprimento mínimo em cm', max_digits=6, null=True)),
                ('max_height', models.DecimalField(blank=True, decimal_places=2, help_text='Altura máxima em cm', max_digits=6, null=True)),
                ('max_width', models.DecimalField(blank=True, decimal_places=2, help_text='Largura máxima em cm', max_digits=6, null=True)),
                ('max_length', models.DecimalField(blank=True, decimal_places=2, help_text='Comprimento máximo em cm', max_digits=6, null=True)),
                ('min_weight', models.DecimalField(blank=True, decimal_places=3, help_text='Peso mínimo em kg', max_digits=6, null=True)),
                ('max_weight', models.DecimalField(blank=True, decimal_places=2, help_text='Peso máximo em kg', max_digits=6, null=True)),
                ('min_sum_dimensions', models.DecimalField(blank=True, decimal_places=2, help_text='Soma mínima das dimensões (L+A+C) em cm', max_digits=6, null=True)),
                ('max_sum_dimensions', models.DecimalField(blank=True, decimal_places=2, help_text='Soma máxima das dimensões (L+A+C) em cm', max_digits=6, null=True)),
                ('max_single_side', models.DecimalField(blank=True, decimal_places=2, help_text='Tamanho máximo de qualquer lado individual em cm', max_digits=6, null=True)),
                ('non_mechanizable_threshold', models.DecimalField(blank=True, decimal_places=2, help_text='Limite em cm acima do qual incide taxa de não mecanizável (ex: 70cm para Correios)', max_digits=6, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Se a regra está ativa. Regras inativas são ignoradas na validação.')),
                ('notes', models.TextField(blank=True, help_text='Observações sobre a regra (ex: taxa extra para >70cm)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Regra de Transportadora',
                'verbose_name_plural': 'Regras de Transportadoras',
                'ordering': ['carrier_name', 'modality'],
                'indexes': [models.Index(fields=['carrier_name'], name='logistics_c_carrier_bed2d0_idx'), models.Index(fields=['is_active'], name='logistics_c_is_acti_0014c8_idx')],
                'unique_together': {('carrier_name', 'modality')},
            },
        ),
    ]
