# Generated by Django 5.1.6 on 2026-02-12 18:54

from django.db import migrations


def seed_carrier_rules(apps, schema_editor):
    """
    Seed default carrier rules based on known carrier policies.

    Each rule represents a modality of a carrier with its dimension/weight constraints.
    Carrier names match what Melhor Envio API returns in company.name.
    """
    CarrierRule = apps.get_model('logistics', 'CarrierRule')

    rules = [
        # =================== Azul Cargo Express ===================
        {
            'carrier_name': 'Azul Cargo Express',
            'modality': 'Azul Expresso',
            'min_height': 15, 'min_width': 15, 'min_length': 15,
            'max_height': 70, 'max_width': 80, 'max_length': 100,
            'min_weight': 0.1, 'max_weight': 60,
            'notes': 'Modalidade expressa Azul Cargo. Dimensoes min 15x15x15cm, max 100x80x70cm.',
        },
        {
            'carrier_name': 'Azul Cargo Express',
            'modality': 'Azul E-Commerce',
            'min_height': 15, 'min_width': 15, 'min_length': 15,
            'max_height': 70, 'max_width': 80, 'max_length': 100,
            'min_weight': 0.1, 'max_weight': 30,
            'notes': 'Modalidade e-commerce Azul Cargo. Peso max 30kg (menor que Expresso).',
        },

        # =================== Buslog ===================
        {
            'carrier_name': 'Buslog',
            'modality': 'Buslog',
            'max_height': 82, 'max_width': 85, 'max_length': 129,
            'max_weight': 50,
            'notes': 'Buslog unidades proprias. Sem dimensoes minimas.',
        },
        {
            'carrier_name': 'Buslog',
            'modality': 'Buslog Pegaki',
            'max_height': 82, 'max_width': 85, 'max_length': 100,
            'max_sum_dimensions': 200,
            'max_weight': 30,
            'notes': 'Buslog via pontos Pegaki. Soma max dimensoes 200cm.',
        },

        # =================== Correios ===================
        {
            'carrier_name': 'Correios',
            'modality': 'SEDEX/PAC',
            'min_height': 1, 'min_width': 8, 'min_length': 13,
            'max_height': 100, 'max_width': 100, 'max_length': 100,
            'max_sum_dimensions': 200,
            'max_weight': 30,
            'non_mechanizable_threshold': 70,
            'notes': (
                'Correios SEDEX e PAC. Soma max 200cm. '
                'Taxa de nao mecanizavel para pacotes com lado >70cm.'
            ),
        },
        {
            'carrier_name': 'Correios',
            'modality': 'Mini Envios',
            'min_height': 1, 'min_width': 8, 'min_length': 13,
            'max_height': 4, 'max_width': 16, 'max_length': 24,
            'max_weight': 0.3,
            'notes': 'Correios Mini Envios. Peso max 300g. Dimensoes muito restritas.',
        },
        {
            'carrier_name': 'Correios',
            'modality': 'Correios Pegaki',
            'max_height': 100, 'max_width': 100, 'max_length': 100,
            'max_sum_dimensions': 200,
            'max_weight': 30,
            'non_mechanizable_threshold': 70,
            'notes': (
                'Correios via pontos Pegaki. Mesmas restricoes de SEDEX/PAC. '
                'Mini Envios max 0.3kg.'
            ),
        },

        # =================== Jadlog ===================
        {
            'carrier_name': 'Jadlog',
            'modality': 'Jadlog',
            'max_height': 80, 'max_width': 80, 'max_length': 80,
            'max_weight': 100,
            'notes': 'Jadlog unidades proprias. Peso max 100kg. Sem dimensoes minimas.',
        },
        {
            'carrier_name': 'Jadlog',
            'modality': 'Jadlog Pegaki',
            'max_height': 80, 'max_width': 80, 'max_length': 80,
            'max_sum_dimensions': 200,
            'max_weight': 30,
            'notes': 'Jadlog via pontos Pegaki. Soma max 200cm.',
        },
        {
            'carrier_name': 'Jadlog',
            'modality': 'Jadlog Parceiro',
            'max_height': 60, 'max_width': 60, 'max_length': 60,
            'max_weight': 10,
            'notes': 'Jadlog via parceiros. Restricoes mais apertadas: 60cm max e 10kg.',
        },

        # =================== J&T Express ===================
        {
            'carrier_name': 'J&T Express',
            'modality': 'J&T Express',
            'max_single_side': 120,
            'max_sum_dimensions': 240,
            'min_weight': 0.01, 'max_weight': 30,
            'notes': (
                'J&T Express. Maior lado max 120cm. '
                'Soma max 240cm. Sem dimensoes minimas por lado.'
            ),
        },
        {
            'carrier_name': 'J&T Express',
            'modality': 'J&T Pegaki',
            'max_height': 100, 'max_width': 100, 'max_length': 100,
            'max_sum_dimensions': 200,
            'max_weight': 30,
            'notes': 'J&T Express via pontos Pegaki.',
        },

        # =================== LATAM Cargo ===================
        {
            'carrier_name': 'LATAM Cargo',
            'modality': 'LATAM Cargo',
            'min_height': 10, 'min_width': 10, 'min_length': 10,
            'max_height': 100, 'max_width': 100, 'max_length': 100,
            'min_weight': 0.1, 'max_weight': 60,
            'notes': 'LATAM Cargo aereo. Min 10x10x10cm, max 100x100x100cm.',
        },
        {
            'carrier_name': 'LATAM Cargo',
            'modality': 'LATAM Pegaki',
            'max_height': 100, 'max_width': 100, 'max_length': 100,
            'max_sum_dimensions': 200,
            'max_weight': 30,
            'notes': 'LATAM Cargo via pontos Pegaki.',
        },

        # =================== Loggi ===================
        {
            'carrier_name': 'Loggi',
            'modality': 'Loggi Express/Ponto',
            'max_height': 100, 'max_width': 100, 'max_length': 100,
            'max_sum_dimensions': 200,
            'max_weight': 30,
            'non_mechanizable_threshold': 70,
            'notes': (
                'Loggi Express e Loggi Ponto. Max 100cm qualquer lado. '
                'Soma max 200cm. Taxa nao mecanizavel >70cm para certos destinos.'
            ),
        },
        {
            'carrier_name': 'Loggi',
            'modality': 'Loggi Coleta',
            'min_height': 1, 'min_width': 10, 'min_length': 15,
            'max_height': 100, 'max_width': 100, 'max_length': 100,
            'min_sum_dimensions': 25,
            'max_sum_dimensions': 200,
            'min_weight': 0.0001, 'max_weight': 30,
            'non_mechanizable_threshold': 70,
            'notes': (
                'Loggi Coleta. Dimensoes min: 1x10x15cm, soma min 25cm. '
                'Taxa nao mecanizavel >70cm para certos destinos.'
            ),
        },
    ]

    for rule_data in rules:
        CarrierRule.objects.create(**rule_data)


def remove_carrier_rules(apps, schema_editor):
    """Remove all seeded carrier rules."""
    CarrierRule = apps.get_model('logistics', 'CarrierRule')
    carrier_names = [
        'Azul Cargo Express', 'Buslog', 'Correios', 'Jadlog',
        'J&T Express', 'LATAM Cargo', 'Loggi',
    ]
    CarrierRule.objects.filter(carrier_name__in=carrier_names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_add_carrier_rule_model'),
    ]

    operations = [
        migrations.RunPython(seed_carrier_rules, remove_carrier_rules),
    ]
