# Generated by Django 5.1.6 on 2026-02-12 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_seed_default_carrier_rules'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inpersondelivery',
            name='completed_by',
        ),
        migrations.AddField(
            model_name='inpersondelivery',
            name='buyer_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inpersondelivery',
            name='buyer_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inpersondelivery',
            name='seller_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inpersondelivery',
            name='seller_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
