# Generated by Django 5.1.6 on 2026-02-15 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0005_add_completion_confirmation_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('created', 'Etiqueta Criada'), ('pending', 'Pendente'), ('released', 'Etiqueta Paga'), ('generated', 'Etiqueta Gerada'), ('posted', 'Postado'), ('in_transit', 'Em Trânsito'), ('out_for_delivery', 'Saiu para Entrega'), ('delivered', 'Entregue'), ('cancelled', 'Cancelado'), ('returned', 'Devolvido')], default='pending', max_length=20),
        ),
    ]
