# Generated by Django 5.1.6 on 2026-02-18 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0007_simplify_shipment_statuses'),
    ]

    operations = [
        migrations.CreateModel(
            name='MelhorEnvioOAuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment', models.CharField(choices=[('sandbox', 'Sandbox'), ('production', 'Production')], default='sandbox', max_length=20)),
                ('access_token', models.TextField(help_text='Token de acesso OAuth 2.0 (validade 30 dias)')),
                ('refresh_token', models.TextField(help_text='Token de atualização OAuth 2.0 (validade 45 dias)')),
                ('token_type', models.CharField(default='Bearer', help_text='Tipo do token (geralmente "Bearer")', max_length=50)),
                ('expires_at', models.DateTimeField(help_text='Data/hora de expiração do access_token')),
                ('refresh_token_expires_at', models.DateTimeField(blank=True, help_text='Data/hora de expiração do refresh_token (45 dias após emissão)', null=True)),
                ('scope', models.TextField(blank=True, help_text='Escopos autorizados')),
                ('is_active', models.BooleanField(default=True, help_text='Indica se este token é o ativo para o ambiente')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_refreshed_at', models.DateTimeField(blank=True, help_text='Última vez que o token foi renovado automaticamente', null=True)),
            ],
            options={
                'verbose_name': 'Token OAuth Melhor Envio',
                'verbose_name_plural': 'Tokens OAuth Melhor Envio',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['environment', 'is_active'], name='logistics_m_environ_c5d152_idx')],
            },
        ),
    ]
