# Generated by Django 5.1.6 on 2026-02-22 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0009_remove_carrier_rule_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerMelhorEnvioToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment', models.CharField(choices=[('sandbox', 'Sandbox'), ('production', 'Production')], default='sandbox', max_length=20)),
                ('access_token', models.TextField(help_text='Token de acesso OAuth 2.0 (validade 30 dias)')),
                ('refresh_token', models.TextField(help_text='Token de atualização OAuth 2.0 (validade 45 dias)')),
                ('token_type', models.CharField(default='Bearer', max_length=50)),
                ('expires_at', models.DateTimeField(help_text='Data/hora de expiração do access_token')),
                ('refresh_token_expires_at', models.DateTimeField(blank=True, help_text='Data/hora de expiração do refresh_token (45 dias após emissão)', null=True)),
                ('last_refreshed_at', models.DateTimeField(blank=True, help_text='Última vez que o token foi renovado automaticamente', null=True)),
                ('scope', models.TextField(blank=True, help_text='Escopos autorizados')),
                ('is_active', models.BooleanField(default=True, help_text='Indica se esta conexão está ativa para o vendedor')),
                ('me_user_id', models.CharField(blank=True, help_text='ID da conta Melhor Envio do vendedor', max_length=100)),
                ('me_email', models.EmailField(blank=True, help_text='Email da conta Melhor Envio do vendedor (para exibição)', max_length=254)),
                ('me_document', models.CharField(blank=True, help_text='CPF/CNPJ registrado na conta ME do vendedor (apenas dígitos)', max_length=20)),
                ('me_firstname', models.CharField(blank=True, help_text='Nome registrado na conta ME do vendedor', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(help_text='Vendedor dono desta credencial ME', on_delete=django.db.models.deletion.CASCADE, related_name='me_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token OAuth ME (Vendedor)',
                'verbose_name_plural': 'Tokens OAuth ME (Vendedores)',
                'indexes': [models.Index(fields=['seller', 'environment', 'is_active'], name='logistics_s_seller__b7a06d_idx')],
                'unique_together': {('seller', 'environment')},
            },
        ),
    ]
