# Generated by Django 5.1.6 on 2026-02-22 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0010_add_seller_melhor_envio_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellermelhorenviotoken',
            name='me_address',
            field=models.ForeignKey(blank=True, help_text='Endereço de envio criado automaticamente a partir da conta ME do vendedor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='me_token', to='logistics.address'),
        ),
    ]
