# Generated by Django 5.1.6 on 2026-02-22 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0011_add_me_address_to_seller_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='melhorenvio_order_ids',
            field=models.JSONField(blank=True, default=list, help_text='Lista de IDs ME quando o listing possui múltiplos pacotes (1 chamada por pacote).'),
        ),
    ]
