# Generated by Django 5.1.6 on 2026-02-28 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0014_add_multi_package_tracking_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inpersondelivery',
            name='buyer_contact_phone',
            field=models.CharField(blank=True, default='', help_text='Telefone do comprador para contato', max_length=20),
        ),
        migrations.AlterField(
            model_name='inpersondelivery',
            name='meeting_address',
            field=models.JSONField(blank=True, default=dict, help_text='Endereço completo do local de encontro'),
        ),
        migrations.AlterField(
            model_name='inpersondelivery',
            name='meeting_location_name',
            field=models.CharField(blank=True, default='', help_text='Nome do local (ex: Shopping X, Estação Y)', max_length=200),
        ),
        migrations.AlterField(
            model_name='inpersondelivery',
            name='seller_contact_phone',
            field=models.CharField(blank=True, default='', help_text='Telefone do vendedor para contato', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderdelivery',
            name='delivery_method',
            field=models.CharField(choices=[('shipping', 'Envio via Transportadora'), ('in_person', 'Frete por conta do Vendedor')], default='shipping', max_length=20),
        ),
    ]
