# Generated by Django 5.1.6 on 2026-03-01 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0015_make_inpersondelivery_meeting_fields_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdelivery',
            name='delivery_method',
            field=models.CharField(choices=[('shipping', 'Envio via Transportadora'), ('in_person', 'Frete por conta do Vendedor'), ('split', 'Entrega Mista (Transportadora + Presencial)')], default='shipping', max_length=20),
        ),
    ]
