# Generated by Django 5.1.6 on 2026-03-01 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0016_add_split_delivery_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdelivery',
            name='shipment',
        ),
        migrations.AddField(
            model_name='shipment',
            name='order_delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_shipments', to='logistics.orderdelivery'),
        ),
    ]
