# Generated by Codex on 2026-05-12

import django.db.models.deletion
from django.db import migrations, models


def backfill_in_person_delivery_order(apps, schema_editor):
    InPersonDelivery = apps.get_model('logistics', 'InPersonDelivery')

    for delivery in InPersonDelivery.objects.filter(order__isnull=True):
        try:
            order_delivery = delivery.order_delivery
        except Exception:
            continue

        if order_delivery and order_delivery.order_id:
            delivery.order_id = order_delivery.order_id
            delivery.save(update_fields=['order'])


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0017_replace_order_delivery_shipment_onetoone_with_fk_on_shipment'),
        ('orders', '0005_add_seller_to_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='inpersondelivery',
            name='order',
            field=models.ForeignKey(
                blank=True,
                help_text='Pedido associado à entrega presencial',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='in_person_deliveries',
                to='orders.order',
            ),
        ),
        migrations.RunPython(
            backfill_in_person_delivery_order,
            migrations.RunPython.noop,
        ),
        migrations.AddIndex(
            model_name='inpersondelivery',
            index=models.Index(fields=['order'], name='logistics_i_order_i_69759b_idx'),
        ),
    ]
